// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by ffigen; the struct helpers it emits are not exercised.
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'dart:ffi' as ffi;

/// [control] Creates an engine with the reference node types registered.
@ffi.Native<ffi.Pointer<AudEngine> Function(ffi.Pointer<AudEngineConfig>)>()
external ffi.Pointer<AudEngine> aud_engine_create(
  ffi.Pointer<AudEngineConfig> config,
);

/// [control] Creates a node instance of a registered type; returns the node
/// id (>= 0) or an error code (< 0).
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudEngine>, ffi.Pointer<ffi.Char>)>()
external int aud_engine_create_node(
  ffi.Pointer<AudEngine> engine,
  ffi.Pointer<ffi.Char> type_id,
);

/// [control] Destroys the engine and every node instance. Stop rendering
/// first.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudEngine>)>()
external void aud_engine_destroy(ffi.Pointer<AudEngine> engine);

/// [control] Destroys a node instance that is not part of the published
/// chain; AUD_ERROR_STATE while it is, or while the realtime thread has not
/// adopted the latest chain yet (it may still render the node).
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudEngine>, ffi.Int32)>()
external int aud_engine_destroy_node(ffi.Pointer<AudEngine> engine, int node);

/// [control] Copies the counters.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<AudEngine>, ffi.Pointer<AudEngineStats>)
>()
external void aud_engine_get_stats(
  ffi.Pointer<AudEngine> engine,
  ffi.Pointer<AudEngineStats> stats,
);

/// [control] The AudHostApi* packages register their node types with.
@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.Pointer<AudEngine>)>()
external ffi.Pointer<ffi.Void> aud_engine_host_api(
  ffi.Pointer<AudEngine> engine,
);

/// [realtime] The render callback of aud_audio_io: `user` is the engine. The
/// signature matches AudRenderCallback of aud_abi.h.
@ffi.Native<
  ffi.Void Function(
    ffi.Pointer<ffi.Void>,
    ffi.Pointer<ffi.Float>,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external void aud_engine_io_render(
  ffi.Pointer<ffi.Void> user,
  ffi.Pointer<ffi.Float> interleaved_output,
  int frames,
  int channels,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudEngine>, ffi.Int32)>()
external int aud_engine_node_type_capabilities(
  ffi.Pointer<AudEngine> engine,
  int index,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AudEngine>, ffi.Int32)>()
external ffi.Pointer<ffi.Char> aud_engine_node_type_id(
  ffi.Pointer<AudEngine> engine,
  int index,
);

@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AudEngine>, ffi.Int32)>()
external ffi.Pointer<ffi.Char> aud_engine_node_type_name(
  ffi.Pointer<AudEngine> engine,
  int index,
);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudEngine>, ffi.Int32)>()
external int aud_engine_node_type_num_params(
  ffi.Pointer<AudEngine> engine,
  int index,
);

/// Fills the parameter's id, unit and range; AUD_OK or an error code.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudEngine>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Pointer<ffi.Char>>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
  )
>()
external int aud_engine_node_type_param(
  ffi.Pointer<AudEngine> engine,
  int index,
  int param,
  ffi.Pointer<ffi.Pointer<ffi.Char>> id,
  ffi.Pointer<ffi.Pointer<ffi.Char>> unit,
  ffi.Pointer<ffi.Float> min_value,
  ffi.Pointer<ffi.Float> max_value,
  ffi.Pointer<ffi.Float> default_value,
);

/// [control] The registered node types.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudEngine>)>()
external int aud_engine_num_node_types(ffi.Pointer<AudEngine> engine);

/// [realtime] Renders `frames` frames of interleaved output. Applies pending
/// commands first, adopts a new chain, runs the nodes, interleaves.
@ffi.Native<
  ffi.Void Function(ffi.Pointer<AudEngine>, ffi.Pointer<ffi.Float>, ffi.Uint32)
>()
external void aud_engine_render(
  ffi.Pointer<AudEngine> engine,
  ffi.Pointer<ffi.Float> interleaved_output,
  int frames,
);

/// [control] Zeroes the counters; the realtime thread keeps counting.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudEngine>)>()
external void aud_engine_reset_stats(ffi.Pointer<AudEngine> engine);

/// [control, one producer] Enqueues a note on (on != 0) or note off.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudEngine>,
    ffi.Int32,
    ffi.Int32,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Float,
  )
>()
external int aud_engine_send_note(
  ffi.Pointer<AudEngine> engine,
  int node,
  int on,
  int channel,
  int number,
  double velocity,
);

/// [control] Publishes a serial chain of node instances as the render
/// program; the realtime thread adopts it at the next block start. Returns
/// the revision (> 0) or an error code.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudEngine>, ffi.Pointer<ffi.Int32>, ffi.Uint32)
>()
external int aud_engine_set_chain(
  ffi.Pointer<AudEngine> engine,
  ffi.Pointer<ffi.Int32> nodes,
  int count,
);

/// [control, one producer] Enqueues a parameter change; AUD_ERROR_QUEUE_FULL
/// when the queue is full - nothing is dropped silently.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudEngine>, ffi.Int32, ffi.Uint32, ffi.Float)
>()
external int aud_engine_set_param(
  ffi.Pointer<AudEngine> engine,
  int node,
  int param,
  double value,
);

/// [control] Applies a string setting to a node on the calling thread; may
/// block (loading). AUD_ERROR_STATE if the node type takes no strings.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudEngine>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Pointer<ffi.Char>,
  )
>()
external int aud_engine_set_string(
  ffi.Pointer<AudEngine> engine,
  int node,
  int key,
  ffi.Pointer<ffi.Char> value,
);

final class AudEngine extends ffi.Opaque {}

/// How an engine is created.
final class AudEngineConfig extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Double()
  external double sample_rate;

  /// the largest block aud_engine_render receives
  @ffi.Uint32()
  external int max_frames;

  /// channels of every bus and of the output
  @ffi.Uint32()
  external int channels;

  /// 0 = 1024
  @ffi.Uint32()
  external int command_queue_capacity;

  /// 0 = 64
  @ffi.Uint32()
  external int max_nodes;

  static ffi.Pointer<AudEngineConfig> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required double sample_rate,
    required int max_frames,
    required int channels,
    required int command_queue_capacity,
    required int max_nodes,
  }) => $allocator<AudEngineConfig>()
    ..ref.struct_size = struct_size
    ..ref.sample_rate = sample_rate
    ..ref.max_frames = max_frames
    ..ref.channels = channels
    ..ref.command_queue_capacity = command_queue_capacity
    ..ref.max_nodes = max_nodes;
}

/// Counters the realtime thread keeps; read with aud_engine_get_stats.
final class AudEngineStats extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// the chain revision the realtime thread uses
  @ffi.Uint32()
  external int program_revision;

  @ffi.Uint64()
  external int blocks_rendered;

  @ffi.Uint64()
  external int frames_rendered;

  @ffi.Uint64()
  external int commands_applied;

  /// enqueue refused because the queue was full
  @ffi.Uint64()
  external int commands_rejected;

  /// enqueue to apply at the block start
  @ffi.Int64()
  external int command_latency_min_ns;

  @ffi.Int64()
  external int command_latency_max_ns;

  @ffi.Int64()
  external int command_latency_sum_ns;

  @ffi.Uint64()
  external int command_latency_count;

  /// time spent inside aud_engine_render
  @ffi.Int64()
  external int render_time_max_ns;

  @ffi.Int64()
  external int render_time_sum_ns;

  /// the largest absolute output sample since the reset
  @ffi.Float()
  external double output_peak;

  static ffi.Pointer<AudEngineStats> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int program_revision,
    required int blocks_rendered,
    required int frames_rendered,
    required int commands_applied,
    required int commands_rejected,
    required int command_latency_min_ns,
    required int command_latency_max_ns,
    required int command_latency_sum_ns,
    required int command_latency_count,
    required int render_time_max_ns,
    required int render_time_sum_ns,
    required double output_peak,
  }) => $allocator<AudEngineStats>()
    ..ref.struct_size = struct_size
    ..ref.program_revision = program_revision
    ..ref.blocks_rendered = blocks_rendered
    ..ref.frames_rendered = frames_rendered
    ..ref.commands_applied = commands_applied
    ..ref.commands_rejected = commands_rejected
    ..ref.command_latency_min_ns = command_latency_min_ns
    ..ref.command_latency_max_ns = command_latency_max_ns
    ..ref.command_latency_sum_ns = command_latency_sum_ns
    ..ref.command_latency_count = command_latency_count
    ..ref.render_time_max_ns = render_time_max_ns
    ..ref.render_time_sum_ns = render_time_sum_ns
    ..ref.output_peak = output_peak;
}
