// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by ffigen; the struct helpers it emits are not exercised.
// coverage:ignore-file

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
import 'package:aud_audio_core/aud_audio_core_bindings.dart' as core;
import 'dart:ffi' as ffi;

/// [control] Opens a transaction; AUD_ERROR_STATE while one is open.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_begin(ffi.Pointer<AudGraph> graph);

/// [control, one producer] Cancels waiting events: those with `id`, or all
/// of `node` when `id` is 0, or every waiting event when both are 0.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Int32, ffi.Uint32)>()
external int aud_graph_cancel(ffi.Pointer<AudGraph> graph, int node, int id);

/// [control] Compiles the topology and publishes the program; returns the
/// revision (> 0) or an error code, e.g. AUD_ERROR_CYCLE. On an error the
/// transaction stays open.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_commit(ffi.Pointer<AudGraph> graph);

/// [control] Connects an output bus to an input bus inside the open
/// transaction; `flags` are AUD_CONNECTION_*. Channels are mapped: equal
/// counts one to one, mono is broadcast, a wider source is averaged into a
/// mono input, otherwise the first channels are mapped.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
    ffi.Uint32,
  )
>()
external int aud_graph_connect(
  ffi.Pointer<AudGraph> graph,
  int from,
  int from_bus,
  int to,
  int to_bus,
  int flags,
);

/// [control] Connects an event output to an event input.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
  )
>()
external int aud_graph_connect_events(
  ffi.Pointer<AudGraph> graph,
  int from,
  int from_port,
  int to,
  int to_port,
);

/// [control] Creates a graph in the created state with the reference nodes
/// registered; NULL for an invalid configuration.
@ffi.Native<ffi.Pointer<AudGraph> Function(ffi.Pointer<AudGraphConfig>)>()
external ffi.Pointer<AudGraph> aud_graph_create(
  ffi.Pointer<AudGraphConfig> config,
);

/// [control] Creates and prepares an instance of a registered type; returns
/// its handle (> 0) or an error code: AUD_ERROR_UNKNOWN_TYPE,
/// AUD_ERROR_FORMAT for channels outside the descriptor's range,
/// AUD_ERROR_CAPACITY when max_nodes is reached. The instance renders from
/// the next commit on.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<AudNodeConfig>,
  )
>()
external int aud_graph_create_node(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<ffi.Char> type_id,
  ffi.Pointer<AudNodeConfig> config,
);

/// [control] Destroys the graph and every instance. The stream must have
/// stopped calling aud_graph_render.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudGraph>)>()
external void aud_graph_destroy(ffi.Pointer<AudGraph> graph);

/// [control] Removes an audio connection inside the open transaction.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
  )
>()
external int aud_graph_disconnect(
  ffi.Pointer<AudGraph> graph,
  int from,
  int from_bus,
  int to,
  int to_bus,
);

/// [control] Removes an event connection.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint32,
  )
>()
external int aud_graph_disconnect_events(
  ffi.Pointer<AudGraph> graph,
  int from,
  int from_port,
  int to,
  int to_port,
);

/// [control] Copies the counters.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Pointer<AudGraphStats>)
>()
external int aud_graph_get_stats(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<AudGraphStats> stats,
);

/// [control] The AudHostApi* packages register their node types and
/// transport providers with.
@ffi.Native<ffi.Pointer<core.AudHostApi> Function(ffi.Pointer<AudGraph>)>()
external ffi.Pointer<core.AudHostApi> aud_graph_host_api(
  ffi.Pointer<AudGraph> graph,
);

/// [control] The prepared largest block.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_max_frames(ffi.Pointer<AudGraph> graph);

/// [control] The channels of a bus of an instance (`direction` 0 input, 1
/// output), or an error code.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Int32, ffi.Uint32, ffi.Uint32)
>()
external int aud_graph_node_channels(
  ffi.Pointer<AudGraph> graph,
  int node,
  int direction,
  int bus,
);

/// [control] The descriptor of an instance; NULL for an unknown handle.
@ffi.Native<
  ffi.Pointer<core.AudNodeDescriptor> Function(ffi.Pointer<AudGraph>, ffi.Int32)
>()
external ffi.Pointer<core.AudNodeDescriptor> aud_graph_node_descriptor(
  ffi.Pointer<AudGraph> graph,
  int node,
);

/// [control] The latency of an instance in frames (its own, plus the fixed
/// block when the engine re-blocks it), or an error code.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Int32)>()
external int aud_graph_node_latency(ffi.Pointer<AudGraph> graph, int node);

/// [control] The frames by which scheduled events of the node are
/// pre-delivered so that they are heard at their time: the path latency
/// from the node to the graph output (graph-001).
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Int32)>()
external int aud_graph_node_lead(ffi.Pointer<AudGraph> graph, int node);

/// [control] Restores a state blob saved by `version` of the node's state
/// format, parked like aud_graph_node_save_state; AUD_ERROR_STATE_VERSION
/// when the node cannot read it.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Uint32,
  )
>()
external int aud_graph_node_load_state(
  ffi.Pointer<AudGraph> graph,
  int node,
  ffi.Pointer<ffi.Void> data,
  int size,
  int version,
);

/// [control] Writes the state of an instance with AUD_NODE_CAP_STATE into
/// `buffer` and its size into `size`; AUD_ERROR_BUFFER_TOO_SMALL with the
/// needed size when `capacity` is too small (`capacity` 0 asks for the
/// size), AUD_ERROR_UNSUPPORTED for a node without state. The ABI tags
/// save_state as [offline]: while the graph runs, the node is parked for
/// the call so that no realtime call of it overlaps - a block rendered
/// meanwhile skips its process call and clears its outputs; its parameter
/// changes, events and transport resets wait for its next block. Not
/// running, the call goes straight through.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Pointer<ffi.Void>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int aud_graph_node_save_state(
  ffi.Pointer<AudGraph> graph,
  int node,
  ffi.Pointer<ffi.Void> buffer,
  int capacity,
  ffi.Pointer<ffi.Size> size,
);

@ffi.Native<
  ffi.Pointer<core.AudNodeDescriptor> Function(ffi.Pointer<AudGraph>, ffi.Int32)
>()
external ffi.Pointer<core.AudNodeDescriptor> aud_graph_node_type(
  ffi.Pointer<AudGraph> graph,
  int index,
);

@ffi.Native<
  ffi.Pointer<core.AudNodeDescriptor> Function(
    ffi.Pointer<AudGraph>,
    ffi.Pointer<ffi.Char>,
  )
>()
external ffi.Pointer<core.AudNodeDescriptor> aud_graph_node_type_by_id(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<ffi.Char> type_id,
);

/// [control] The live handles in creation order; returns the number of
/// nodes and writes at most `capacity` of them.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Pointer<ffi.Int32>, ffi.Uint32)
>()
external int aud_graph_nodes(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<ffi.Int32> handles,
  int capacity,
);

/// [control] The registered node types.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_num_node_types(ffi.Pointer<AudGraph> graph);

/// [control] The latency of the published program from the graph inputs to
/// the graph outputs in frames.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_output_latency(ffi.Pointer<AudGraph> graph);

/// [control] The tail of the published program in frames: the longest
/// node tail plus the path latency from that node to the graph outputs,
/// AUD_TAIL_INFINITE when a contributing node reports an infinite tail.
/// Retired nodes still rendering their tails count until they finish.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_output_tail(ffi.Pointer<AudGraph> graph);

/// [control] Prepares every instance for a sample rate and a largest block
/// (0 keeps the current value), resets the time filter and the transport
/// snapshot and recompiles the program; AUD_ERROR_STATE while running.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Double, ffi.Uint32)>()
external int aud_graph_prepare(
  ffi.Pointer<AudGraph> graph,
  double sample_rate,
  int max_frames,
);

/// [control] Removes a node inside the open transaction: its connections
/// go with it, the instance retires at the commit and is freed once its
/// fade or tail has passed (AUD_NOTIFY_NODE_DONE). A node that never
/// rendered is freed at once.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Int32)>()
external int aud_graph_remove_node(ffi.Pointer<AudGraph> graph, int node);

/// [realtime] Renders one block into the host's buses: the render function
/// of plugin-002, `user` is the graph. Blocks longer than the prepared
/// maximum are refused with AUD_ERROR_INVALID_ARGUMENT and silence; a graph
/// that is not running renders silence and returns AUD_OK.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<ffi.Void>, ffi.Pointer<core.AudRenderRequest>)
>()
external int aud_graph_render(
  ffi.Pointer<ffi.Void> user,
  ffi.Pointer<core.AudRenderRequest> request,
);

/// [realtime] Renders one block like aud_graph_render and hands the events
/// that reached the graph's event input to the host: the render call of
/// the plugin shells (plugin-002). `num_output_events` and
/// `dropped_output_events` are written before the call returns.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Pointer<AudHostRenderRequest>)
>()
external int aud_graph_render_host(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<AudHostRenderRequest> request,
);

/// [control] Renders offline on the calling thread while no stream renders;
/// the graph has to be running.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Pointer<AudOfflineRequest>)
>()
external int aud_graph_render_offline(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<AudOfflineRequest> request,
);

/// [control] Zeroes the counters; the realtime thread keeps counting.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudGraph>)>()
external void aud_graph_reset_stats(ffi.Pointer<AudGraph> graph);

/// [control] Resumes rendering after a suspension.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_resume(ffi.Pointer<AudGraph> graph);

/// [control] The revision the realtime thread adopted last.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_revision(ffi.Pointer<AudGraph> graph);

/// [control] Discards the open transaction.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_rollback(ffi.Pointer<AudGraph> graph);

/// [control] The sample position of the next block.
@ffi.Native<ffi.Int64 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_sample_position(ffi.Pointer<AudGraph> graph);

/// [control] The prepared sample rate.
@ffi.Native<ffi.Double Function(ffi.Pointer<AudGraph>)>()
external double aud_graph_sample_rate(ffi.Pointer<AudGraph> graph);

/// [control, one producer] Enqueues an event for `node` at `at` (NULL means
/// the next block). The event's sample offset is ignored; its port names
/// the event input. An `id` above zero lets the event be cancelled while it
/// waits. AUD_ERROR_LOOKAHEAD beyond the lookahead, AUD_ERROR_CAPACITY when
/// the scheduler is full - an event with a time holds its place from the
/// enqueue until it leaves the scheduler, so a burst within one block
/// cannot overrun it -, AUD_ERROR_STATE for a node that has not been
/// committed, AUD_ERROR_RETIRED for a removed node.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Pointer<core.AudEvent>,
    ffi.Pointer<core.AudTimestamp>,
    ffi.Uint32,
  )
>()
external int aud_graph_send_event(
  ffi.Pointer<AudGraph> graph,
  int node,
  ffi.Pointer<core.AudEvent> event,
  ffi.Pointer<core.AudTimestamp> at,
  int id,
);

/// [control] Sets the listener the notification thread wakes; NULL removes
/// it.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    AudGraphListener,
    ffi.Pointer<ffi.Void>,
  )
>()
external int aud_graph_set_listener(
  ffi.Pointer<AudGraph> graph,
  AudGraphListener listener,
  ffi.Pointer<ffi.Void> user,
);

/// [control, one producer] Enqueues a parameter change for the next block;
/// a node that has not rendered yet takes it at once. AUD_ERROR_QUEUE_FULL
/// when the queue is full - nothing is dropped silently.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Float,
    ffi.Uint32,
  )
>()
external int aud_graph_set_param(
  ffi.Pointer<AudGraph> graph,
  int node,
  int param,
  double value,
  int ramp_frames,
);

/// [control] Applies a string setting on the calling thread; may block.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Pointer<ffi.Char>,
  )
>()
external int aud_graph_set_string(
  ffi.Pointer<AudGraph> graph,
  int node,
  int key,
  ffi.Pointer<ffi.Char> value,
);

/// [control] Selects a registered transport provider by id (NULL or the
/// internal id selects the internal transport); AUD_ERROR_STATE while
/// running.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Pointer<ffi.Char>)>()
external int aud_graph_set_transport_provider(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<ffi.Char> id,
);

/// [control] Starts rendering from the prepared or stopped state.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_start(ffi.Pointer<AudGraph> graph);

/// [control] The AUD_GRAPH_* state.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_state(ffi.Pointer<AudGraph> graph);

/// [control] Stops rendering: running notes are closed, the transport stops
/// and the time filter resets. Returns when no render is in flight.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_stop(ffi.Pointer<AudGraph> graph);

/// [control] Suspends rendering: blocks render silence, the transport and
/// the pending events stay. Returns when no render is in flight.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudGraph>)>()
external int aud_graph_suspend(ffi.Pointer<AudGraph> graph);

/// [control] Takes the waiting notifications, at most `capacity`, and frees
/// the instances that finished; returns the number taken.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Pointer<AudGraphNotification>,
    ffi.Uint32,
  )
>()
external int aud_graph_take_notifications(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<AudGraphNotification> out,
  int capacity,
);

/// [control] The peak and root mean square of the last block a tap saw.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Pointer<ffi.Float>,
    ffi.Pointer<ffi.Float>,
  )
>()
external int aud_graph_tap_meter(
  ffi.Pointer<AudGraph> graph,
  int node,
  int channel,
  ffi.Pointer<ffi.Float> peak,
  ffi.Pointer<ffi.Float> rms,
);

/// [control] Copies the most recent `frames` frames of `channel` of a tap
/// node into `out`; frames the tap has not seen yet are 0.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Int32,
    ffi.Uint32,
    ffi.Pointer<ffi.Float>,
    ffi.Uint32,
  )
>()
external int aud_graph_tap_read(
  ffi.Pointer<AudGraph> graph,
  int node,
  int channel,
  ffi.Pointer<ffi.Float> out,
  int frames,
);

/// [control, one producer] Enqueues a transport request; the provider
/// applies it on the realtime thread at the request's time.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudGraph>,
    ffi.Pointer<core.AudTransportRequest>,
  )
>()
external int aud_graph_transport(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<core.AudTransportRequest> request,
);

/// [control] Reads the transport as the realtime thread last published it.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudGraph>, ffi.Pointer<AudGraphTransportState>)
>()
external int aud_graph_transport_state(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<AudGraphTransportState> state,
);

/// Whether the watchdog is compiled in.
@ffi.Native<ffi.Int32 Function()>()
external int aud_graph_watchdog_enabled();

/// [any thread] Zeroes the process-wide count.
@ffi.Native<ffi.Void Function()>()
external void aud_graph_watchdog_reset();

/// [any thread] The violations every graph of the process counted since
/// the last reset; 0 without the watchdog.
@ffi.Native<ffi.Uint64 Function()>()
external int aud_graph_watchdog_violations();

/// [control] Applies a node preset (JSON of aud_node_preset.schema.json) to
/// the node `node_id`: the strings on the calling thread, the state blob
/// through the node park, the parameters through the queue. A preset the
/// validation refuses changes nothing; a part the node or a full queue
/// refuses while it is applied stops it there - the parts before stay, and
/// the host's table holds what the node has.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudHost>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
  )
>()
external int aud_host_apply_preset(
  ffi.Pointer<AudHost> host,
  ffi.Pointer<ffi.Char> node_id,
  ffi.Pointer<ffi.Char> json,
  int length,
);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudHost>,
    ffi.Uint32,
    ffi.Pointer<AudHostAsset>,
  )
>()
external int aud_host_asset(
  ffi.Pointer<AudHost> host,
  int index,
  ffi.Pointer<AudHostAsset> out,
);

/// [control] Creates a host over a graph; the host never destroys the
/// graph. NULL for an invalid argument.
@ffi.Native<
  ffi.Pointer<AudHost> Function(
    ffi.Pointer<AudGraph>,
    ffi.Pointer<AudHostOptions>,
  )
>()
external ffi.Pointer<AudHost> aud_host_create(
  ffi.Pointer<AudGraph> graph,
  ffi.Pointer<AudHostOptions> options,
);

/// [control] Destroys the host; the graph and its nodes stay.
@ffi.Native<ffi.Void Function(ffi.Pointer<AudHost>)>()
external void aud_host_destroy(ffi.Pointer<AudHost> host);

/// [control] The current value of a parameter by its stable id.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudHost>, ffi.Uint32, ffi.Pointer<ffi.Float>)
>()
external int aud_host_get_param(
  ffi.Pointer<AudHost> host,
  int id,
  ffi.Pointer<ffi.Float> value,
);

/// [control] The graph of the host.
@ffi.Native<ffi.Pointer<AudGraph> Function(ffi.Pointer<AudHost>)>()
external ffi.Pointer<AudGraph> aud_host_graph(ffi.Pointer<AudHost> host);

/// [control] Reads the buses, the counts and the name of a document text
/// without a graph; AUD_ERROR_INVALID_ARGUMENT for text that is no
/// document, AUD_ERROR_CAPACITY for more buses than the info holds.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<AudHostDocumentInfo>,
  )
>()
external int aud_host_inspect(
  ffi.Pointer<ffi.Char> json,
  int length,
  ffi.Pointer<AudHostDocumentInfo> info,
);

/// [control] What the last failed call of the host complained about, or an
/// empty string; valid until the next call.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AudHost>)>()
external ffi.Pointer<ffi.Char> aud_host_last_error(ffi.Pointer<AudHost> host);

/// [control] The latency and the tail of the published program:
/// aud_graph_output_latency and aud_graph_output_tail.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudHost>)>()
external int aud_host_latency(ffi.Pointer<AudHost> host);

/// [control] Loads a document: validates all of it - the schema, the types
/// registered with the graph, the ids, the buses against the graph's, the
/// parameters and string keys, the state versions, the assets on disk, the
/// parameter ids - and only then creates the nodes, applies their presets
/// and connects them in one transaction while the nodes of the previous
/// document retire. On an error nothing of the document is applied; the
/// error code names the first problem and aud_host_last_error says which.
/// The transport settings are sent after the commit: AUD_ERROR_QUEUE_FULL
/// then means the document is loaded but the event queue refused them.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudHost>, ffi.Pointer<ffi.Char>, ffi.Size)
>()
external int aud_host_load(
  ffi.Pointer<AudHost> host,
  ffi.Pointer<ffi.Char> json,
  int length,
);

/// [control] The handle of the node `id` of the loaded document, or
/// AUD_ERROR_NOT_FOUND.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudHost>, ffi.Pointer<ffi.Char>)>()
external int aud_host_node(ffi.Pointer<AudHost> host, ffi.Pointer<ffi.Char> id);

@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudHost>, ffi.Uint32)>()
external int aud_host_node_at(ffi.Pointer<AudHost> host, int index);

/// [control] The document id of a node handle; NULL for a handle the
/// document does not know.
@ffi.Native<ffi.Pointer<ffi.Char> Function(ffi.Pointer<AudHost>, ffi.Int32)>()
external ffi.Pointer<ffi.Char> aud_host_node_id(
  ffi.Pointer<AudHost> host,
  int node,
);

/// [control] Writes the preset of the node `node_id` with its current
/// parameters, strings and state as JSON text, like aud_host_save.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudHost>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int aud_host_node_preset(
  ffi.Pointer<AudHost> host,
  ffi.Pointer<ffi.Char> node_id,
  ffi.Pointer<ffi.Char> buffer,
  int capacity,
  ffi.Pointer<ffi.Size> size,
);

/// [control] The assets of the loaded document.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudHost>)>()
external int aud_host_num_assets(ffi.Pointer<AudHost> host);

/// [control] The nodes of the loaded document, and the handle of the node at
/// `index` in document order (AUD_ERROR_NOT_FOUND beyond them).
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudHost>)>()
external int aud_host_num_nodes(ffi.Pointer<AudHost> host);

/// [control] The parameters of the loaded document, ordered by id.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudHost>)>()
external int aud_host_num_params(ffi.Pointer<AudHost> host);

@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudHost>,
    ffi.Uint32,
    ffi.Pointer<AudHostParam>,
  )
>()
external int aud_host_param(
  ffi.Pointer<AudHost> host,
  int index,
  ffi.Pointer<AudHostParam> out,
);

/// [any thread] The stable id of a parameter: FNV-1a over the node id, a
/// slash and the parameter id, the top bit cleared; 0 for a NULL argument.
@ffi.Native<ffi.Uint32 Function(ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external int aud_host_param_id(
  ffi.Pointer<ffi.Char> node_id,
  ffi.Pointer<ffi.Char> param_id,
);

/// [control] The index of the parameter with the stable `id`, or
/// AUD_ERROR_NOT_FOUND.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<AudHost>, ffi.Uint32)>()
external int aud_host_param_index(ffi.Pointer<AudHost> host, int id);

/// [realtime] Renders one block: aud_graph_render_host on the host's graph.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudHost>, ffi.Pointer<AudHostRenderRequest>)
>()
external int aud_host_render(
  ffi.Pointer<AudHost> host,
  ffi.Pointer<AudHostRenderRequest> request,
);

/// [control] Writes the loaded document with the current state - the
/// parameters, the string settings, the state blobs of the nodes and the
/// asset table - as JSON text into `buffer` and its length into `size`;
/// AUD_ERROR_BUFFER_TOO_SMALL with the needed length when `capacity` is
/// smaller than the length plus the terminator. The connections are those
/// of the loaded document; edits made on the graph directly are not part
/// of it.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudHost>,
    ffi.Pointer<ffi.Char>,
    ffi.Size,
    ffi.Pointer<ffi.Size>,
  )
>()
external int aud_host_save(
  ffi.Pointer<AudHost> host,
  ffi.Pointer<ffi.Char> buffer,
  int capacity,
  ffi.Pointer<ffi.Size> size,
);

/// [control] Relinks an asset: the new path is resolved and checked, every
/// string setting that names the asset is applied again, and the saved
/// document carries the new path (relative to the base directory when it
/// lies inside it).
@ffi.Native<
  ffi.Int32 Function(
    ffi.Pointer<AudHost>,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<ffi.Char>,
  )
>()
external int aud_host_set_asset_path(
  ffi.Pointer<AudHost> host,
  ffi.Pointer<ffi.Char> id,
  ffi.Pointer<ffi.Char> path,
);

/// [control, one producer] Sets a parameter by its stable id like
/// aud_graph_set_param; AUD_ERROR_INVALID_ARGUMENT for a value outside the
/// parameter's range, which no document could load again.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<AudHost>, ffi.Uint32, ffi.Float, ffi.Uint32)
>()
external int aud_host_set_param(
  ffi.Pointer<AudHost> host,
  int id,
  double value,
  int ramp_frames,
);

@ffi.Native<ffi.Uint32 Function(ffi.Pointer<AudHost>)>()
external int aud_host_tail(ffi.Pointer<AudHost> host);

const int AUD_CONNECTION_LOW_LATENCY = 1;

const int AUD_FILTER_PARAM_CUTOFF = 0;

const int AUD_FILTER_PARAM_MODE = 2;

const int AUD_FILTER_PARAM_RESONANCE = 1;

const int AUD_GRAPH_CREATED = 0;

const int AUD_GRAPH_DISPOSED = 5;

const int AUD_GRAPH_DROP_LATE_EVENTS = 1;

const int AUD_GRAPH_ERROR_REALTIME_VIOLATION = -100;

const String AUD_GRAPH_FEEDBACK_TYPE_ID = 'aud.graph.feedback';

const String AUD_GRAPH_FILTER_TYPE_ID = 'aud.graph.filter';

const String AUD_GRAPH_INTERNAL_TRANSPORT_ID = 'aud.graph.transport';

const String AUD_GRAPH_MIXER_TYPE_ID = 'aud.graph.mixer';

const int AUD_GRAPH_NODE = 0;

const String AUD_GRAPH_OSCILLATOR_TYPE_ID = 'aud.graph.oscillator';

const int AUD_GRAPH_PREPARED = 1;

const int AUD_GRAPH_RUNNING = 2;

const int AUD_GRAPH_STOPPED = 4;

const int AUD_GRAPH_SUSPENDED = 3;

const String AUD_GRAPH_TAP_TYPE_ID = 'aud.graph.tap';

const int AUD_GRAPH_VIOLATION_ALLOC = 4;

const int AUD_GRAPH_VIOLATION_DELETE = 2;

const int AUD_GRAPH_VIOLATION_FREE = 8;

const int AUD_GRAPH_VIOLATION_LOG = 16;

const int AUD_GRAPH_VIOLATION_NEW = 1;

const int AUD_HOST_MAX_BUSES = 16;

const int AUD_HOST_MAX_NAME = 128;

const int AUD_MIXER_NUM_INPUTS = 8;

const int AUD_MIXER_PARAM_MASTER = 8;

const int AUD_NOTIFY_DIAGNOSTIC = 4;

const int AUD_NOTIFY_EVENT = 5;

const int AUD_NOTIFY_NODE_DONE = 3;

const int AUD_NOTIFY_REVISION = 1;

const int AUD_NOTIFY_STATE = 2;

const int AUD_NOTIFY_TIME_RESET = 7;

const int AUD_NOTIFY_TRANSPORT = 6;

const int AUD_OSCILLATOR_PARAM_AMPLITUDE = 1;

const int AUD_OSCILLATOR_PARAM_FREQUENCY = 0;

const int AUD_OSCILLATOR_PARAM_WAVEFORM = 2;

final class AudGraph extends ffi.Opaque {}

/// How a graph is created. Zero means the default.
final class AudGraphConfig extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Double()
  external double sample_rate;

  /// the largest block aud_graph_render receives
  @ffi.Uint32()
  external int max_frames;

  @ffi.Uint32()
  external int num_input_buses;

  /// channels per graph input bus
  external ffi.Pointer<ffi.Uint32> input_channels;

  @ffi.Uint32()
  external int num_output_buses;

  /// channels per graph output bus
  external ffi.Pointer<ffi.Uint32> output_channels;

  /// AUD_GRAPH_*
  @ffi.Uint32()
  external int flags;

  /// 0 = 256
  @ffi.Uint32()
  external int max_nodes;

  /// 0 = 1024
  @ffi.Uint32()
  external int max_connections;

  /// 0 = 1024
  @ffi.Uint32()
  external int param_queue_capacity;

  /// 0 = 4096
  @ffi.Uint32()
  external int event_queue_capacity;

  /// 0 = 4096
  @ffi.Uint32()
  external int scheduler_capacity;

  /// 0 = 1024
  @ffi.Uint32()
  external int notification_capacity;

  /// 0 = 1024, the budget of interop-002
  @ffi.Uint32()
  external int max_events_per_block;

  /// 0 = 5 ms at the sample rate
  @ffi.Uint32()
  external int fade_frames;

  /// 0 = 10 s at the sample rate
  @ffi.Uint32()
  external int max_tail_frames;

  /// 0 = 10 s
  @ffi.Int64()
  external int lookahead_ns;

  static ffi.Pointer<AudGraphConfig> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required double sample_rate,
    required int max_frames,
    required int num_input_buses,
    required ffi.Pointer<ffi.Uint32> input_channels,
    required int num_output_buses,
    required ffi.Pointer<ffi.Uint32> output_channels,
    required int flags,
    required int max_nodes,
    required int max_connections,
    required int param_queue_capacity,
    required int event_queue_capacity,
    required int scheduler_capacity,
    required int notification_capacity,
    required int max_events_per_block,
    required int fade_frames,
    required int max_tail_frames,
    required int lookahead_ns,
  }) => $allocator<AudGraphConfig>()
    ..ref.struct_size = struct_size
    ..ref.sample_rate = sample_rate
    ..ref.max_frames = max_frames
    ..ref.num_input_buses = num_input_buses
    ..ref.input_channels = input_channels
    ..ref.num_output_buses = num_output_buses
    ..ref.output_channels = output_channels
    ..ref.flags = flags
    ..ref.max_nodes = max_nodes
    ..ref.max_connections = max_connections
    ..ref.param_queue_capacity = param_queue_capacity
    ..ref.event_queue_capacity = event_queue_capacity
    ..ref.scheduler_capacity = scheduler_capacity
    ..ref.notification_capacity = notification_capacity
    ..ref.max_events_per_block = max_events_per_block
    ..ref.fade_frames = fade_frames
    ..ref.max_tail_frames = max_tail_frames
    ..ref.lookahead_ns = lookahead_ns;
}

/// Wakes the control thread: notifications wait. Called on the notification
/// thread, never on the realtime thread.
typedef AudGraphListener =
    ffi.Pointer<ffi.NativeFunction<AudGraphListenerFunction>>;
typedef AudGraphListenerFunction =
    ffi.Void Function(ffi.Pointer<ffi.Void> user);
typedef DartAudGraphListenerFunction =
    void Function(ffi.Pointer<ffi.Void> user);

/// A notification of the realtime thread.
final class AudGraphNotification extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// AUD_NOTIFY_*
  @ffi.Uint32()
  external int type;

  @ffi.Int32()
  external int node;

  @ffi.Int32()
  external int code;

  @ffi.Uint32()
  external int revision;

  @ffi.Uint32()
  external int count;

  /// the block it happened in
  @ffi.Int64()
  external int sample_position;

  @ffi.Int64()
  external int value;

  @ffi.Double()
  external double number;

  external core.AudEvent event;

  static ffi.Pointer<AudGraphNotification> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int type,
    required int node,
    required int code,
    required int revision,
    required int count,
    required int sample_position,
    required int value,
    required double number,
    required core.AudEvent event,
  }) => $allocator<AudGraphNotification>()
    ..ref.struct_size = struct_size
    ..ref.type = type
    ..ref.node = node
    ..ref.code = code
    ..ref.revision = revision
    ..ref.count = count
    ..ref.sample_position = sample_position
    ..ref.value = value
    ..ref.number = number
    ..ref.event = event;
}

/// The counters of a graph.
final class AudGraphStats extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int state;

  /// the adopted revision
  @ffi.Uint32()
  external int revision;

  /// events waiting in the scheduler
  @ffi.Uint32()
  external int scheduled;

  @ffi.Uint64()
  external int blocks_rendered;

  @ffi.Uint64()
  external int frames_rendered;

  @ffi.Int64()
  external int render_time_max_ns;

  @ffi.Int64()
  external int render_time_sum_ns;

  @ffi.Uint64()
  external int events_delivered;

  @ffi.Uint64()
  external int events_late;

  @ffi.Uint64()
  external int events_dropped;

  @ffi.Uint64()
  external int params_applied;

  /// enqueues the control thread refused
  @ffi.Uint64()
  external int rejected;

  @ffi.Uint64()
  external int notifications_dropped;

  @ffi.Uint64()
  external int overloads;

  @ffi.Uint32()
  external int time_filter_resets;

  @ffi.Uint32()
  external int reserved;

  /// the largest absolute output sample since the reset
  @ffi.Float()
  external double output_peak;

  @ffi.Uint32()
  external int reserved2;

  /// what the watchdog caught since the reset
  @ffi.Uint64()
  external int realtime_violations;

  static ffi.Pointer<AudGraphStats> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int state,
    required int revision,
    required int scheduled,
    required int blocks_rendered,
    required int frames_rendered,
    required int render_time_max_ns,
    required int render_time_sum_ns,
    required int events_delivered,
    required int events_late,
    required int events_dropped,
    required int params_applied,
    required int rejected,
    required int notifications_dropped,
    required int overloads,
    required int time_filter_resets,
    required int reserved,
    required double output_peak,
    required int reserved2,
    required int realtime_violations,
  }) => $allocator<AudGraphStats>()
    ..ref.struct_size = struct_size
    ..ref.state = state
    ..ref.revision = revision
    ..ref.scheduled = scheduled
    ..ref.blocks_rendered = blocks_rendered
    ..ref.frames_rendered = frames_rendered
    ..ref.render_time_max_ns = render_time_max_ns
    ..ref.render_time_sum_ns = render_time_sum_ns
    ..ref.events_delivered = events_delivered
    ..ref.events_late = events_late
    ..ref.events_dropped = events_dropped
    ..ref.params_applied = params_applied
    ..ref.rejected = rejected
    ..ref.notifications_dropped = notifications_dropped
    ..ref.overloads = overloads
    ..ref.time_filter_resets = time_filter_resets
    ..ref.reserved = reserved
    ..ref.output_peak = output_peak
    ..ref.reserved2 = reserved2
    ..ref.realtime_violations = realtime_violations;
}

/// The transport as the realtime thread last saw it.
final class AudGraphTransportState extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int playing;

  /// ticks
  @ffi.Int64()
  external int beat;

  @ffi.Double()
  external double tempo;

  @ffi.Uint32()
  external int numerator;

  @ffi.Uint32()
  external int denominator;

  @ffi.Uint32()
  external int looping;

  @ffi.Uint32()
  external int reserved;

  @ffi.Int64()
  external int loop_start;

  @ffi.Int64()
  external int loop_end;

  static ffi.Pointer<AudGraphTransportState> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int playing,
    required int beat,
    required double tempo,
    required int numerator,
    required int denominator,
    required int looping,
    required int reserved,
    required int loop_start,
    required int loop_end,
  }) => $allocator<AudGraphTransportState>()
    ..ref.struct_size = struct_size
    ..ref.playing = playing
    ..ref.beat = beat
    ..ref.tempo = tempo
    ..ref.numerator = numerator
    ..ref.denominator = denominator
    ..ref.looping = looping
    ..ref.reserved = reserved
    ..ref.loop_start = loop_start
    ..ref.loop_end = loop_end;
}

/// ............................................................................
/// The headless host (plugin-002, ticket 20)
///
/// A host over a graph that works without Dart: it loads a graph document
/// (doc/schemas/aud_graph_document.schema.json with the node presets of
/// aud_node_preset.schema.json of the core) in one transaction, applies the
/// presets, resolves the assets the document references, saves the whole
/// state back as a document and gives the plugin shells what they need:
/// stable parameter ids, latency, tail and the events of the graph per
/// block. Every function is [control] except aud_host_render. A failed call
/// leaves a message in aud_host_last_error.
///
/// Presets apply in the order strings, state, parameters: the strings load
/// what a node needs, the state blob restores what parameters cannot hold,
/// the parameters come last. The host keeps the value of every parameter -
/// the engine has none to report - and assumes the descriptor's default for
/// one that no preset names; a saved document names them all. A node whose
/// state blob holds parameter values therefore has them overridden by the
/// parameters of the preset.
///
/// Assets: the document's `assets` table maps an id to a path; a string
/// setting whose value is `asset:<id>` names one. The host resolves the
/// path against its base directory, checks that the file exists before
/// anything is applied and hands the resolved path to the node's
/// set_string, which loads the file.
///
/// Parameter ids: FNV-1a over `<node id>/<parameter id>` with the top bit
/// cleared - 31 bits, as VST3 hosts expect (JUCE clears the same bit), and
/// never the invalid id 0xFFFFFFFF of VST3 and CLAP. A document whose ids
/// collide is refused.
final class AudHost extends ffi.Opaque {}

/// One asset of the loaded document. The strings stay valid until the next
/// load or aud_host_set_asset_path.
final class AudHostAsset extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// whether the file was found at the last check
  @ffi.Uint32()
  external int exists;

  external ffi.Pointer<ffi.Char> id;

  /// as the document names it
  external ffi.Pointer<ffi.Char> path;

  /// what the nodes receive
  external ffi.Pointer<ffi.Char> resolved;

  static ffi.Pointer<AudHostAsset> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int exists,
    required ffi.Pointer<ffi.Char> id,
    required ffi.Pointer<ffi.Char> path,
    required ffi.Pointer<ffi.Char> resolved,
  }) => $allocator<AudHostAsset>()
    ..ref.struct_size = struct_size
    ..ref.exists = exists
    ..ref.id = id
    ..ref.path = path
    ..ref.resolved = resolved;
}

/// What aud_host_inspect reads from a document without a graph: its buses,
/// so that a shell can create the graph that fits, and its counts.
final class AudHostDocumentInfo extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int schema;

  @ffi.Uint32()
  external int num_input_buses;

  @ffi.Uint32()
  external int num_output_buses;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint32> input_channels;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.Uint32> output_channels;

  @ffi.Uint32()
  external int num_nodes;

  @ffi.Uint32()
  external int num_assets;

  @ffi.Array.multi([128])
  external ffi.Array<ffi.Char> name;
}

/// How a host is created. NULL or zero means the default.
final class AudHostOptions extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// Relative asset paths resolve against it; NULL leaves them relative to
  /// the working directory.
  external ffi.Pointer<ffi.Char> base_directory;

  static ffi.Pointer<AudHostOptions> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required ffi.Pointer<ffi.Char> base_directory,
  }) => $allocator<AudHostOptions>()
    ..ref.struct_size = struct_size
    ..ref.base_directory = base_directory;
}

/// One parameter of the loaded document. The strings stay valid until the
/// next load.
final class AudHostParam extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// the stable id
  @ffi.Uint32()
  external int id;

  /// the node handle
  @ffi.Int32()
  external int node;

  /// the index in the node's descriptor
  @ffi.Uint32()
  external int index;

  external ffi.Pointer<ffi.Char> node_id;

  external ffi.Pointer<ffi.Char> param_id;

  external ffi.Pointer<core.AudParamDescriptor> descriptor;

  /// the current value as the host set it
  @ffi.Float()
  external double value;

  static ffi.Pointer<AudHostParam> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int id,
    required int node,
    required int index,
    required ffi.Pointer<ffi.Char> node_id,
    required ffi.Pointer<ffi.Char> param_id,
    required ffi.Pointer<core.AudParamDescriptor> descriptor,
    required double value,
  }) => $allocator<AudHostParam>()
    ..ref.struct_size = struct_size
    ..ref.id = id
    ..ref.node = node
    ..ref.index = index
    ..ref.node_id = node_id
    ..ref.param_id = param_id
    ..ref.descriptor = descriptor
    ..ref.value = value;
}

/// What a host that wants the graph's events hands to one render call
/// (plugin-002, ticket 20): the render request of the ABI and a buffer the
/// engine fills with the events that reached the graph's event input in the
/// block - node 0's input 0, where event connections "to the graph" end -
/// in ascending sample offset. A host that renders through
/// aud_graph_render_host takes these events; rendered through
/// aud_graph_render they reach the control thread as AUD_NOTIFY_EVENT.
/// With AUD_PROCESS_OFFLINE in `flags` the block renders freewheeling: the
/// nodes see the flag and no overload is reported.
final class AudHostRenderRequest extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// AUD_PROCESS_*
  @ffi.Uint32()
  external int flags;

  /// the buses, time, events and transport
  external ffi.Pointer<core.AudRenderRequest> request;

  /// written by the engine
  external ffi.Pointer<core.AudEvent> output_events;

  /// 0: the events stay notifications
  @ffi.Uint32()
  external int max_output_events;

  /// written by the engine
  @ffi.Uint32()
  external int num_output_events;

  /// did not fit; also a diagnostic
  @ffi.Uint32()
  external int dropped_output_events;

  @ffi.Uint32()
  external int reserved;

  static ffi.Pointer<AudHostRenderRequest> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int flags,
    required ffi.Pointer<core.AudRenderRequest> request,
    required ffi.Pointer<core.AudEvent> output_events,
    required int max_output_events,
    required int num_output_events,
    required int dropped_output_events,
    required int reserved,
  }) => $allocator<AudHostRenderRequest>()
    ..ref.struct_size = struct_size
    ..ref.flags = flags
    ..ref.request = request
    ..ref.output_events = output_events
    ..ref.max_output_events = max_output_events
    ..ref.num_output_events = num_output_events
    ..ref.dropped_output_events = dropped_output_events
    ..ref.reserved = reserved;
}

/// How a node instance is created: its bus formats. NULL or zero bus counts
/// take the default channels of the descriptor.
final class AudNodeConfig extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  /// the descriptor's count, or 0
  @ffi.Uint32()
  external int num_input_buses;

  external ffi.Pointer<ffi.Uint32> input_channels;

  @ffi.Uint32()
  external int num_output_buses;

  external ffi.Pointer<ffi.Uint32> output_channels;

  /// aud.graph.feedback: the delay; 0 = max_frames
  @ffi.Uint32()
  external int delay_frames;

  @ffi.Uint32()
  external int reserved;

  static ffi.Pointer<AudNodeConfig> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int num_input_buses,
    required ffi.Pointer<ffi.Uint32> input_channels,
    required int num_output_buses,
    required ffi.Pointer<ffi.Uint32> output_channels,
    required int delay_frames,
    required int reserved,
  }) => $allocator<AudNodeConfig>()
    ..ref.struct_size = struct_size
    ..ref.num_input_buses = num_input_buses
    ..ref.input_channels = input_channels
    ..ref.num_output_buses = num_output_buses
    ..ref.output_channels = output_channels
    ..ref.delay_frames = delay_frames
    ..ref.reserved = reserved;
}

/// Rendering offline: `frames` frames in blocks of `block_frames`, or in the
/// cycle of `block_sizes`, from `inputs` into `outputs` (planar, `frames`
/// long, as many buses as the graph has; NULL inputs are silent) on a
/// virtual timeline: the host time runs from `start_host_time_ns` with the
/// sample clock.
final class AudOfflineRequest extends ffi.Struct {
  @ffi.Uint32()
  external int struct_size;

  @ffi.Uint32()
  external int frames;

  /// 0 = max_frames
  @ffi.Uint32()
  external int block_frames;

  @ffi.Uint32()
  external int num_block_sizes;

  external ffi.Pointer<ffi.Uint32> block_sizes;

  external ffi.Pointer<core.AudAudioBus> inputs;

  external ffi.Pointer<core.AudAudioBus> outputs;

  @ffi.Int64()
  external int start_sample_position;

  @ffi.Int64()
  external int start_host_time_ns;

  static ffi.Pointer<AudOfflineRequest> $allocate(
    ffi.Allocator $allocator, {
    required int struct_size,
    required int frames,
    required int block_frames,
    required int num_block_sizes,
    required ffi.Pointer<ffi.Uint32> block_sizes,
    required ffi.Pointer<core.AudAudioBus> inputs,
    required ffi.Pointer<core.AudAudioBus> outputs,
    required int start_sample_position,
    required int start_host_time_ns,
  }) => $allocator<AudOfflineRequest>()
    ..ref.struct_size = struct_size
    ..ref.frames = frames
    ..ref.block_frames = block_frames
    ..ref.num_block_sizes = num_block_sizes
    ..ref.block_sizes = block_sizes
    ..ref.inputs = inputs
    ..ref.outputs = outputs
    ..ref.start_sample_position = start_sample_position
    ..ref.start_host_time_ns = start_host_time_ns;
}
