// @license
// Copyright (c) Audanika. All Rights Reserved.
//
// Use of this source code is governed by terms that can be
// found in the LICENSE file in the root of this package.

// Generated by scripts/generate-abi-constants.js from the ffigen bindings.
// Do not edit; run the script after ffigen.

// ignore_for_file: constant_identifier_names

const int AUD_CONNECTION_LOW_LATENCY = 1;
const int AUD_FILTER_PARAM_CUTOFF = 0;
const int AUD_FILTER_PARAM_MODE = 2;
const int AUD_FILTER_PARAM_RESONANCE = 1;
const int AUD_GRAPH_CREATED = 0;
const int AUD_GRAPH_DISPOSED = 5;
const int AUD_GRAPH_DROP_LATE_EVENTS = 1;
const int AUD_GRAPH_ERROR_REALTIME_VIOLATION = -100;
const String AUD_GRAPH_FEEDBACK_TYPE_ID = 'aud.graph.feedback';
const String AUD_GRAPH_FILTER_TYPE_ID = 'aud.graph.filter';
const String AUD_GRAPH_INTERNAL_TRANSPORT_ID = 'aud.graph.transport';
const String AUD_GRAPH_MIXER_TYPE_ID = 'aud.graph.mixer';
const int AUD_GRAPH_NODE = 0;
const String AUD_GRAPH_OSCILLATOR_TYPE_ID = 'aud.graph.oscillator';
const int AUD_GRAPH_PREPARED = 1;
const int AUD_GRAPH_RUNNING = 2;
const int AUD_GRAPH_STOPPED = 4;
const int AUD_GRAPH_SUSPENDED = 3;
const String AUD_GRAPH_TAP_TYPE_ID = 'aud.graph.tap';
const int AUD_GRAPH_VIOLATION_ALLOC = 4;
const int AUD_GRAPH_VIOLATION_DELETE = 2;
const int AUD_GRAPH_VIOLATION_FREE = 8;
const int AUD_GRAPH_VIOLATION_LOG = 16;
const int AUD_GRAPH_VIOLATION_NEW = 1;
const int AUD_HOST_MAX_BUSES = 16;
const int AUD_HOST_MAX_NAME = 128;
const int AUD_MIXER_NUM_INPUTS = 8;
const int AUD_MIXER_PARAM_MASTER = 8;
const int AUD_NOTIFY_DIAGNOSTIC = 4;
const int AUD_NOTIFY_EVENT = 5;
const int AUD_NOTIFY_NODE_DONE = 3;
const int AUD_NOTIFY_REVISION = 1;
const int AUD_NOTIFY_STATE = 2;
const int AUD_NOTIFY_TIME_RESET = 7;
const int AUD_NOTIFY_TRANSPORT = 6;
const int AUD_OSCILLATOR_PARAM_AMPLITUDE = 1;
const int AUD_OSCILLATOR_PARAM_FREQUENCY = 0;
const int AUD_OSCILLATOR_PARAM_WAVEFORM = 2;
